/* Drop old tables then make the new ones*/
DROP TABLE IF EXISTS KillerAddons;
DROP TABLE IF EXISTS Killers;
DROP TABLE IF EXISTS KillerPerks;
DROP TABLE IF EXISTS Offerings;

CREATE TABLE Killers (
    killer_id int NOT NULL AUTO_INCREMENT,
    killerName varchar(30) NOT NULL,
    imageLocation varchar(30),
    PRIMARY KEY(killer_id)
);
CREATE TABLE KillerAddons(
    add_id int NOT NULL AUTO_INCREMENT,
    killer_id int NOT NULL,
    addonName varchar(50) NOT NULL,
    addonDesc varchar(500),
    imageLocation varchar(30),
    PRIMARY KEY(add_id),
    FOREIGN KEY (killer_id) REFERENCES Killers(killer_id)
);
CREATE TABLE KillerPerks(
    kPerk_id int NOT NULL AUTO_INCREMENT,
    perkName varchar(30) NOT NULL,
    perkDesc varchar(500),
    imageLocation varchar(30),
    PRIMARY KEY(kPerk_id)
);
CREATE TABLE Offerings(
    o_id int NOT NULL AUTO_INCREMENT,
    offeringName varchar(30) NOT NULL,
    offeringDesc varchar(500),
    imageLocation varchar(30),
    PRIMARY KEY(o_id)
);

/*Killers*/

INSERT INTO Killers (killer_id,killerName,imageLocation) values (0,'The Trapper',NULL);
INSERT INTO Killers (killer_id,killerName,imageLocation) values (0,'The Wraith',NULL);
INSERT INTO Killers (killer_id,killerName,imageLocation) values (0,'The Hillbilly',NULL);
INSERT INTO Killers (killer_id,killerName,imageLocation) values (0,'The Nurse',NULL);
INSERT INTO Killers (killer_id,killerName,imageLocation) values (0,'The Shape',NULL);
INSERT INTO Killers (killer_id,killerName,imageLocation) values (0,'The Hag',NULL);
INSERT INTO Killers (killer_id,killerName,imageLocation) values (0,'The Doctor',NULL);
INSERT INTO Killers (killer_id,killerName,imageLocation) values (0,'The Huntress',NULL);
INSERT INTO Killers (killer_id,killerName,imageLocation) values (0,'The Cannibal',NULL);
INSERT INTO Killers (killer_id,killerName,imageLocation) values (0,'The Nightmare',NULL);
INSERT INTO Killers (killer_id,killerName,imageLocation) values (0,'The Pig',NULL);
INSERT INTO Killers (killer_id,killerName,imageLocation) values (0,'The Clown',NULL);
INSERT INTO Killers (killer_id,killerName,imageLocation) values (0,'The Spirit',NULL);
INSERT INTO Killers (killer_id,killerName,imageLocation) values (0,'The Legion',NULL);
INSERT INTO Killers (killer_id,killerName,imageLocation) values (0,'The Plague',NULL);
INSERT INTO Killers (killer_id,killerName,imageLocation) values (0,'The Ghost Face',NULL);
INSERT INTO Killers (killer_id,killerName,imageLocation) values (0,'The Demogorgon',NULL);
INSERT INTO Killers (killer_id,killerName,imageLocation) values (0,'The Oni',NULL);
INSERT INTO Killers (killer_id,killerName,imageLocation) values (0,'The Deathslinger',NULL);
INSERT INTO Killers (killer_id,killerName,imageLocation) values (0,'The Executioner',NULL);
INSERT INTO Killers (killer_id,killerName,imageLocation) values (0,'The Blight',NULL);
INSERT INTO Killers (killer_id,killerName,imageLocation) values (0,'The Twins',NULL);
INSERT INTO Killers (killer_id,killerName,imageLocation) values (0,'The Trickster',NULL);
INSERT INTO Killers (killer_id,killerName,imageLocation) values (0,'The Nemesis',NULL);
INSERT INTO Killers (killer_id,killerName,imageLocation) values (0,'The Cenobite',NULL);
INSERT INTO Killers (killer_id,killerName,imageLocation) values (0,'The Artist',NULL);
INSERT INTO Killers (killer_id,killerName,imageLocation) values (0,'The Onryo',NULL);
INSERT INTO Killers (killer_id,killerName,imageLocation) values (0,'The Dredge',NULL);
INSERT INTO Killers (killer_id,killerName,imageLocation) values (0,'The Mastermind',NULL);

/*Perks*/

INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'A Nurse\'s Calling',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Agitation',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Awakened Awareness',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Bamboozle',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Barbecue & Chilli',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Beast of Prey',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Bitter Murmur',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Blood Echo',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Blood Warden',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Bloodhound',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Brutal Strength',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Call of Brine',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Corrupt Intervention',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Coulrophobia',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Coup de Grace',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Claustrophobia',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Dark Devotion',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Darkness Revealed',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Dead Man\'s Switch',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Deadlock',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Deathbound',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Deerstalker',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Discordance',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Dissolution',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Distressing',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Dragon\'s Grip',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Dying Light',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Enduring',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Eruption',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Fearmonger',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Fire Up',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Forced Penance',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Franklin\'s Demise',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Furtive Chase',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Gearhead',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Grim Embrace',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Hangman\'s Trick',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Hex: Blood Favour',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Hex: Crowd Control',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Hex: Devour Hope',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Hex: Haunted Ground',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Hex: Huntress Lullaby',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Hex: No One Escapes Death',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Hex: Pentimento',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Hex: Plaything',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Hex: Retribution',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Hex: Ruin',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Hex: The Third Seal',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Hex: Thrill of the Hunt',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Hex: Undying',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Hoarder',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Hysteria',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'I\'m All Ears',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Infectious Fright',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Insidious',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Iron Grasp',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Iron Maiden',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Jolt',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Knock Out',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Lethal Pursuer',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Lightborn',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Mad Grit',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Make Your Choice',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Merciless Storm',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Monitor & Abuse',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Nemesis',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'No Way Out',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Oppression',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Overcharge',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Overwhelming Presence',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Play with Your Food',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Pop Goes the Weasel',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Predator',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Rancor',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Remember Me',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Save the Best for Last',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Scourge Hook: Floods of Rage',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Scourge Hook: Gift of Pain',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Scourge Hook: Monstrous Shrine',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Scourge Hook: Pain Resonance',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Septic Touch',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Shadowborn',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Shattered Hope',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Sloppy Butcher',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Spies from the Shadows',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Spirit Fury',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Starstruck',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Stridor',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Superior Anatomy',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Surveillance',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Terminus',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Territorial Imperative',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Thanatophobia',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Thrilling Tremors',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Tinkerer',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Trail of Torment',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Unnerving Presence',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Unrelenting',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Whispers',NULL,NULL);
INSERT INTO KillerPerks (kPerk_id,perkName,perkDesc,imageLocation) values (0,'Zanshin Tactics',NULL,NULL);

/*Offerings*/

INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Escape! Cake',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Hollow Shell',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Sealed Envelope',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Survivor Pudding',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Bloody Party Streamers',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Bound Envelope',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Tanager Wreath',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Devout Tanager Wreath',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Ardent Tanager Wreath',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Raven Wreath',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Devout Raven Wreath',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Ardent Raven Wreath',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Spotted Owl Wreath',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Devout Spotted Owl Wreath',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Ardent Spotted Owl Wreath',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Shrike Wreath',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Devout Shrike Wreath',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Ardent Shrike Wreath',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Chalk Pouch',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Cream Chalk Pouch',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Ivory Chalk Pouch',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Salt Pouch',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Black Salt Statuette',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Vigo\'s Jar of Salty Lips',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Bloodied Blueprint',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Torn Blueprint',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Scratched Coin',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Tarnished Coin',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Cut Coin',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Shiny Coin',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Clear Reagent',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Faint Reagent',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Hazy Reagent',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Murky Reagent',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Annotated Blueprint',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Vigo\'s Blueprint',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Mouldy Oak',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Rotten Oak',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Putrid Oak',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Petrified Oak',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Cypress Memento Mori',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Ivory Memento Mori',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Ebony Memento Mori',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Azarov\'s Key',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Grandma\'s Cookbook',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Heart Locket',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Charred Wedding Photograph',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Crow\'s Eye',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Jigsaw Piece',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Dusty Noose',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Strode Realty Key',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Shattered Glasses',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'MacMillan\'s Phalanx Bone',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Damaged Photo',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'RPD Badge',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'The Last Mask',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Mary\'s Letter',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'The Pied Piper',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Ichorous Loam',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Yamaoka Family Crest',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Shroud of Union',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Shroud of Separation',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Vigo\'s Shroud',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Shroud of Binding',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Sacrificial Ward',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'Black Ward',NULL,NULL);
INSERT INTO Offerings (o_id,offeringName,offeringDesc,imageLocation) values (0,'White Ward',NULL,NULL);

/*Addons*/

INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,12,'VHS Porn',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,12,'Robin Feather',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,12,'Party Bottle',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,12,'Fingerless Parade Gloves',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,12,'Thick Cork Stopper',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,12,'Sticky Soda Bottle',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,12,'Starling Feather',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,12,'Solvent Jug',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,12,'Kerosene Can',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,12,'Sulphuric Acid Vial',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,12,'Spirit of Hartshorn',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,12,'Smelly Inner Soles',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,12,'Flask of Bleach',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,12,'Bottle of Chloroform',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,12,'Garish Make-Up Kit',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,12,'Ether 15 Vol%',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,12,'Cigar Box',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,12,'Cheap Gin Bottle',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,12,'Tattoo\'s Middle Finger',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,12,'Redhead\'s Pinkie Finger',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,1,'Trapper Gloves',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,1,'Padded Jaws',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,1,'Makeshift Wrap',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,1,'Bear Oil',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,1,'Wax Brick',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,1,'Serrated Jaws',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,1,'Lengthened Jaws',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,1,'Coffee Grounds',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,1,'4-Coil Spring Kit',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,1,'Trapper Bag',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,1,'Tar Bottle',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,1,'Secondary Coil',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,1,'Rusted Jaws',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,1,'Fastening Tools',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,1,'Trapper Sack',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,1,'Tension Spring',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,1,'Oily Coil',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,1,'Honing Stone',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,1,'Iridescent Stone',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,1,'Bloody Coil',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,26,'Vibrant Obituary',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,26,'Thick Tar',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,26,'Oil Paints',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,26,'Choclo Corn',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,26,'Velvet Fabric',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,26,'Untitled Agony',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,26,'Still Life Crow',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,26,'Festering Carrion',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,26,'Automatic Drawing',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,26,'Thorny Nest',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,26,'Silver Bell',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,26,'O Grief, O Lover',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,26,'Darkest Ink',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,26,'Charcoal Stick',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,26,'Severed Tongue',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,26,'Severed Hands',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,26,'Matias\' Baby Shoes',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,26,'Ink Egg',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,26,'Iridescent Feather',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,26,'Garden of Rot',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,6,'Rope Necklet',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,6,'Powdered Eggshell',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,6,'Dead Fly Mud',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,6,'Bog Water',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,6,'Pussy Willow Catkins',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,6,'Half Eggshell',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,6,'Dragonfly Wings',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,6,'Cypress Necklet',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,6,'Bloodied Water',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,6,'Willow Wreath',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,6,'Swamp Orchid Necklet',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,6,'Dried Cicada',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,6,'Cracked Turtle Egg',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,6,'Bloodied Mud',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,6,'Scarred Hand',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,6,'Rusty Shackles',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,6,'Grandma\'s Heart',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,6,'Disfigured Ear',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,6,'Waterlogged Shoe',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,6,'Mint Rag',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,21,'Placebo Tablet',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,21,'Foxglove',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,21,'Compound Seven',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,21,'Chipped Monocle',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,21,'Shredded Notes',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,21,'Pustula Dust',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,21,'Plague Bile',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,21,'Canker Thorn',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,21,'Blighted Rat',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,21,'Umbra Salts',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,21,'Rose Tonic',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,21,'Compound Twenty-One',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,21,'Blighted Crow',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,21,'Adrenaline Vial',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,21,'Vigo\'s Journal',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,21,'Summoning Stone',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,21,'Soul Chemical',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,21,'Alchemist\'s Ring',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,21,'Iridescent Blight Tag',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,21,'Compound Thirty-Three',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,22,'Toy Sword',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,22,'Tiny Fingernail',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,22,'Soured Milk',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,22,'Cat Figurine',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,22,'Madeleine\'s Glove',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,22,'Ceremonial Candelabrum',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,22,'Cat\'s Eye',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,22,'Bloody Black Hood',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,22,'Baby Teeth',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,22,'Weighty Rattle',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,22,'Stale Biscuit',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,22,'Sewer Sludge',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,22,'Rusted Needle',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,22,'Madeleine\'s Scarf',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,22,'Victor\'s Soldier',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,22,'Spinning Top',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,22,'Forest Stew',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,22,'Drop of Perfume',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,22,'Silencing Cloth',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,22,'Iridescent Pendant',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,9,'Vegetable Oil',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,9,'Spark Plug',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,9,'Speed Limiter',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,9,'Chainsaw File',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,9,'Long Guide Bar',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,9,'Primer Bulb',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,9,'Knife Scratches',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,9,'Homemade Muffler',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,9,'Chilli',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,9,'The Grease',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,9,'The Beast\'s Marks',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,9,'Shop Lubricant',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,9,'Grisly Chains',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,9,'Begrimed Chains',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,9,'Rusted Chains',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,9,'Light Chassis',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,9,'Depth Gauge Rake',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,9,'Award-winning Chilli',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,9,'Iridescent Flesh',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,9,'Carburettor Tuning Guide',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,7,'Mouldy Electrode',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,7,'Maple Knight',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,7,'"Order" - Class I',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,7,'"Calm" - Class I',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,7,'Polished Electrode',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,7,'"Restraint" - Class II',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,7,'"Order" - Class II',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,7,'"Discipline" - Class II',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,7,'"Calm" - Class II',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,7,'Scrapped Tape',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,7,'Interview Tape',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,7,'High Stimulus Electrode',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,7,'"Restraint" - Class III',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,7,'"Discipline" - Class III',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,7,'"Restraint" - Carter\'s Notes',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,7,'"Order" - Carter\'s Notes',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,7,'"Discipline" - Carter\'s Notes',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,7,'"Calm" - Carter\'s Notes',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,7,'Iridescent Queen',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,7,'Iridescent King',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,3,'Steel Toe Boots',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,3,'Junkyard Air Filter',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,3,'Heavy Clutch',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,3,'Speed Limiter',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,3,'Dad\'s Boots',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,3,'Punctured Muffler',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,3,'Off-Brand Motor Oil',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,3,'Death Engravings',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,3,'Big Buckle',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,3,'Mother\'s Helpers',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,3,'Low Kickback Chains',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,3,'Leafy Mash',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,3,'Doom Engravings',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,3,'Black Grease',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,3,'Tuned Carburettor',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,3,'Spiked Boots',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,3,'Pighouse Gloves',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,3,'LoPro Chains',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,3,'Apex Muffler',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,3,'Iridescent Brick',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,27,'Videotape Copy',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,27,'Old Newspaper',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,27,'Mother\'s Mirror',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,27,'Cabin Sign',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,27,'Yoichi\'s Fishing Net',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,27,'Well Stone',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,27,'Sea-Soaked Cloth',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,27,'Reiko\'s Watch',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,27,'Clump of Hair',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,27,'Well Water',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,27,'Ring Drawing',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,27,'Rickety Pinwheel',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,27,'Mother\'s Comb',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,27,'Bloody Fingernails',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,27,'VCR',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,27,'Telephone',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,27,'Tape Editing Deck',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,27,'Distorted Photo',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,27,'Remote Control',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,27,'Iridescent Videotape',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,10,'Wool Shirt',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,10,'Sheep Block',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,10,'Kid\'s Drawing',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,10,'Garden Rake',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,10,'Prototype Claws',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,10,'Outdoor Rope',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,10,'Nancy\'s Sketch',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,10,'Green Dress',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,10,'Cat Block',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,10,'Unicorn Block',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,10,'Paint Thinner',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,10,'Nancy\'s Masterpiece',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,10,'Jump Rope',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,10,'Blue Dress',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,10,'Pill Bottle',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,10,'Swing Chains',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,10,'Class Photo',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,10,'"Z" Block',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,10,'Red Paint Brush',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,10,'Black Box',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,5,'Tacky Earrings',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,5,'Memorial Flower',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,5,'Boyfriend\'s Memo',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,5,'Blond Hair',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,5,'Reflective Fragment',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,5,'Jewellery',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,5,'Hair Brush',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,5,'Glass Fragment',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,5,'Dead Rabbit',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,5,'Mirror Shard',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,5,'Judith\'s Journal',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,5,'Jewellery Box',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,5,'J. Myers Memorial',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,5,'Hair Bow',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,5,'Vanity Mirror',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,5,'Tombstone Piece',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,5,'Scratched Mirror',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,5,'Lock of Hair',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,5,'Judith\'s Tombstone',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,5,'Fragrant Tuft of Hair',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,14,'Smiley Face Pin',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,14,'Scratched Ruler',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,14,'Mischief List',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,14,'Friendship Bracelet',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,14,'Never-Sleep Pills',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,14,'Mural Sketch',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,14,'Julie\'s Mix Tape',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,14,'Etched Ruler',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,14,'Defaced Smiley Pin',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,14,'The Legion Pin',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,14,'Susie\'s Mix Tape',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,14,'Stolen Sketch Book',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,14,'Stylish Sunglasses',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,14,'Joey\'s Mix Tape',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,14,'Stab Wounds Study',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,14,'Frank\'s Mix Tape',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,14,'Filthy Blade',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,14,'BFFs',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,14,'Iridescent Button',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,14,'Fuming Mix Tape',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,8,'Yellowed Cloth',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,8,'Coarse Stone',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,8,'Bandaged Haft',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,8,'Amanita Toxin',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,8,'Weighted Head',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,8,'Shiny Pin',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,8,'Oak Haft',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,8,'Manna Grass Braid',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,8,'Leather Loop',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,8,'Venomous Concoction',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,8,'Rusty Head',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,8,'Rose Root',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,8,'Flower Babushka',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,8,'Deerskin Gloves',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,8,'Wooden Fox',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,8,'Infantry Belt',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,8,'Glowing Concoction',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,8,'Begrimed Head',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,8,'Soldier\'s Puttee',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,8,'Iridescent Head',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,11,'Shattered Syringe',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,11,'John\'s Medical File',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,11,'Interlocking Razor',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,11,'Combat Straps',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,11,'Workshop Grease',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,11,'Utility Blades',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,11,'Razor Wires',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,11,'Last Will',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,11,'Face Mask',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,11,'Slow-Release Toxin',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,11,'Rusty Attachments',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,11,'Rules Set No.2',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,11,'Jigsaw\'s Annotated Plan',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,11,'Bag of Gears',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,11,'Tampered Timer',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,11,'Jigsaw\'s Sketch',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,11,'Crate of Gears',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,11,'Amanda\'s Secret',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,11,'Amanda\'s Letter',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,11,'Video Tape',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,16,'"Philly"',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,16,'Walleye\'s Matchbook',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,16,'Headline Cut-Outs',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,16,'Cheap Cologne',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,16,'Telephoto Lens',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,16,'Cinch Straps',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,16,'Olsen\'s Journal',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,16,'Olsen\'s Address Book',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,16,'Marked Map',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,16,'Olsen\'s Wallet',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,16,'Leather Knife Sheath',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,16,'Lasting Perfume',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,16,'Knife Belt Clip',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,16,'Chewed Pen',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,16,'Victim\'s Detailed Routine',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,16,'Night Vision Monocular',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,16,'Drop-Leg Knife Sheath',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,16,'Driver\'s License',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,16,'"Ghost Face Caught on Tape"',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,16,'Outdoor Security Camera',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,17,'Rotten Pumpkin',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,17,'Black Heart',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,17,'Rat Liver',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,17,'Rat Tail',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,17,'Sticky Lining',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,17,'Viscous Webbing',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,17,'Rotten Green Tripe',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,17,'Mews\' Guts',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,17,'Barb\'s Glasses',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,17,'Eleven\'s Soda',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,17,'Thorny Vines',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,17,'Brass Case Lighter',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,17,'Violet Waxcap',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,17,'Deer Lung',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,17,'Lifeguard Whistle',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,17,'Vermilion Webcap',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,17,'Upside Down Resin',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,17,'Unknown Egg',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,17,'Leprose Lichen',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,17,'Red Moss',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,19,'Spit Polish Rag',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,19,'Snake Oil',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,19,'Rickety Chain',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,19,'Modified Ammo Belt',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,19,'Rusted Spike',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,19,'Poison Oak Leaves',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,19,'Marshal\'s Badge',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,19,'Jaw Smasher',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,19,'Chewing Tobacco',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,19,'Warden\'s Keys',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,19,'Wanted Poster',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,19,'Tin Oil Can',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,19,'Honey Locust Thorn',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,19,'Bayshore\'s Gold Tooth',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,19,'Prison Chain',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,19,'Gold Creek Whiskey',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,19,'Bayshore\'s Cigar',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,19,'Barbed Wire',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,19,'Iridescent Coin',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,19,'Hellshire Iron',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,28,'Wooden Plank',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,28,'Mortar and Pestle',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,28,'Follower\'s Cowl',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,28,'Caffeine Tablets',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,28,'Malthinker\'s Skull',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,28,'Haddie\'s Calendar',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,28,'Fallen Shingle',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,28,'Burnt Letters',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,28,'Air Freshener',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,28,'Worry Stone',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,28,'War Helmet',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,28,'Ottomarian Writing',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,28,'Destroyed Pillow',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,28,'Broken Doll',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,28,'Tilling Blade',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,28,'Lavalier Microphone',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,28,'Field Recorder',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,28,'Boat Key',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,28,'Sacrificial Knife',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,28,'Iridescent Wooden Plank',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,20,'Lead Ring',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,20,'Dead Butterfly',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,20,'Copper Ring',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,20,'Black Strap',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,20,'Wax Doll',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,20,'Spearhead',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,20,'Leopard-Print Fabric',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,20,'Forgotten Videotape',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,20,'Cinderella Music Box',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,20,'Valtiel Sect Photograph',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,20,'Tablet of the Oppressor',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,20,'Misty Day, Remains of Judgement',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,20,'Mannequin Foot',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,20,'Burning Man Painting',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,20,'Scarlet Egg',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,20,'Rust-Coloured Egg',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,20,'Lost Memories Book',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,20,'Crimson Ceremony Book',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,20,'Obsidian Goblet',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,20,'Iridescent Seal of Metatron',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,23,'Trick Pouch',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,23,'Memento Blades',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,23,'Killing Part Chords',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,23,'Inferno Wires',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,23,'Tequila Moonrock',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,23,'On Target Single',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,23,'Lucky Blade',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,23,'Ji-Woon\'s Autograph',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,23,'Caged Heart Shoes',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,23,'Melodious Murder',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,23,'Waiting For You Watch',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,23,'Ripper Brace',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,23,'Fizz-Spin Soda',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,23,'Bloody Boa',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,23,'Trick Blades',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,23,'Edge of Revival Album',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,23,'Diamond Cufflinks',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,23,'Cut Thru U Single',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,23,'Iridescent Photocard',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,23,'Death Throes Compilation',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,4,'Wooden Horse',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,4,'White Nit Comb',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,4,'Plaid Flannel',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,4,'Metal Spoon',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,4,'Pocket Watch',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,4,'Dull Bracelet',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,4,'Dark Cincture',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,4,'Catatonic Boy\'s Treasure',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,4,'Bad Man Keepsake',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,4,'Spasmodic Breath',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,4,'Heavy Panting',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,4,'Fragile Wheeze',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,4,'Ataxic Respiration',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,4,'Anxious Gasp',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,4,'Kavanagh\'s Last Breath',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,4,'Jenner\'s Last Breath',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,4,'Campbell\'s Last Breath',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,4,'"Bad Man\'s" Last Breath',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,4,'Torn Bookmark',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,4,'Matchbox',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,25,'Leather Strip',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,25,'Lively Crickets',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,25,'Burning Candle',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,25,'Bent Nail',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,25,'Wriggling Maggots',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,25,'Spoiled Meal',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,25,'Skewered Rat',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,25,'Liquified Gore',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,25,'Flickering Television',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,25,'Torture Pillar',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,25,'Slice of Frank',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,25,'Larry\'s Remains',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,25,'Larry\'s Blood',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,25,'Frank\'s Heart',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,25,'Original Pain',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,25,'Impaling Wire',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,25,'Greasy Black Lens',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,25,'Chatterer\'s Tooth',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,25,'Iridescent Lament Configuration',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,25,'Engineer\'s Fang',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,24,'Visitor Wristband',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,24,'S.T.A.R.S. Field Combat Manual',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,24,'Damaged Syringe',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,24,'Brian\'s Intestine',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,24,'Zombie Heart',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,24,'Mikhail\'s Eye',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,24,'Marvin\'s Blood',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,24,'Adrenaline Injector',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,24,'Admin Wristband',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,24,'Tyrant Gore',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,24,'T-Virus Sample',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,24,'Serotonin Injector',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,24,'Plant 43 Vines',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,24,'Licker Tongue',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,24,'NE-a Parasite',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,24,'Jill\'s Sandwich',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,24,'Depleted Ink Ribbon',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,24,'Broken Recovery Coin',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,24,'Shattered S.T.A.R.S. Badge',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,24,'Iridescent Umbrella Badge',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,15,'Prayer Tablet Fragment',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,15,'Olibanum Incense',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,15,'Limestone Seal',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,15,'Healing Salve',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,15,'Prophylactic Amulet',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,15,'Potent Tincture',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,15,'Haematite Seal',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,15,'Emetic Potion',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,15,'Blessed Apple',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,15,'Rubbing Oil',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,15,'Infected Emetic',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,15,'Incensed Ointment',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,15,'Exorcism Amulet',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,15,'Ashen Apple',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,15,'Worship Tablet',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,15,'Vile Emetic',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,15,'Severed Toe',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,15,'Devotee\'s Amulet',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,15,'Iridescent Seal',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,15,'Black Incense',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,2,'"The Serpent" - Soot',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,2,'"The Hound" - Soot',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,2,'"The Ghost" - Soot',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,2,'"The Beast" - Soot',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,2,'Bone Clapper',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,2,'"Blink" - Mud',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,2,'"Windstorm" - Mud',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,2,'"Swift Hunt" - Mud',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,2,'"Blind Warrior" - Mud',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,2,'"Windstorm" - White',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,2,'"Swift Hunt" - White',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,2,'"Shadow Dance" - White',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,2,'"Blink" - White',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,2,'"Blind Warrior" - White',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,2,'"Windstorm" - Blood',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,2,'"Swift Hunt" - Blood',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,2,'"Shadow Dance" - Blood',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,2,'"All Seeing" - Blood',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,2,'Coxcombed Clapper',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,2,'"All Seeing" - Spirit',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,13,'Zori',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,13,'Shiawase Amulet',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,13,'Origami Crane',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,13,'Gifted Bamboo Comb',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,13,'White Hair Ribbon',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,13,'Rin\'s Broken Watch',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,13,'Muddy Sports Day Cap',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,13,'Kaiun Talisman',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,13,'Juniper Bonsai',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,13,'Rusty Flute',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,13,'Senko Hanabi',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,13,'Katana Tsuba',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,13,'Uchiwa',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,13,'Mother\'s Glasses',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,13,'Yakuyoke Amulet',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,13,'Wakizashi Saya',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,13,'Furin',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,13,'Dried Cherry Blossom',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,13,'Mother-Daughter Ring',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,13,'Kintsugi Teacup',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,18,'Rotting Rope',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,18,'Paper Lantern',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,18,'Cracked Sakazuki',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,18,'Blackened Toenail',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,18,'Polished Maedate',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,18,'Ink Lion',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,18,'Chipped Saihai',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,18,'Child\'s Wooden Sword',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,18,'Bloody Sash',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,18,'Yamaoka Sashimono',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,18,'Wooden Oni Mask',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,18,'Shattered Wakizashi',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,18,'Scalped Topknot',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,18,'Kanai-Anzen Talisman',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,18,'Tear Soaked Tenugui',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,18,'Splintered Hull',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,18,'Lion Fang',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,18,'Akito\'s Crutch',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,18,'Renjiro\'s Bloody Glove',NULL,NULL);
INSERT INTO KillerAddons (add_id,killer_id,addonName,addonDesc,imageLocation) values (0,18,'Iridescent Family Crest',NULL,NULL);
